"""evaluations table

Revision ID: 26318c0a6029
Revises: 1cf1241b2874
Create Date: 2026-09-16 18:40:41.198585

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26318c0a6029"
down_revision: str | Sequence[str] | None = "1cf1241b2874"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("message_id", sa.String(length=64), nullable=False),
        sa.Column("criterio", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("justificacion", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evaluations_message_id"), "evaluations", ["message_id"], unique=False)
    op.create_index(op.f("ix_evaluations_session_id"), "evaluations", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evaluations_session_id"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_message_id"), table_name="evaluations")
    op.drop_table("evaluations")
    # ### end Alembic commands ###
