"""leads table

Revision ID: 9c1dc6720df0
Revises:
Create Date: 2026-09-15 15:18:26.919368

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c1dc6720df0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leads",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=True),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("canal_preferido", sa.String(length=16), nullable=True),
        sa.Column("consentimiento_contacto", sa.Boolean(), nullable=False),
        sa.Column("uso_principal", sa.String(length=16), nullable=True),
        sa.Column("tipo_vehiculo_interes", sa.String(length=16), nullable=True),
        sa.Column("motorizacion_interes", sa.String(length=16), nullable=True),
        sa.Column("nivel_interes", sa.String(length=8), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("leads")
    # ### end Alembic commands ###
