"""feedback message column

Revision ID: aa3ad54be751
Revises: 26318c0a6029
Create Date: 2026-09-17 10:37:13.564194

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa3ad54be751"
down_revision: str | Sequence[str] | None = "26318c0a6029"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("feedback", sa.Column("message", sa.Text(), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feedback", "message")
    # ### end Alembic commands ###
