"""handoffs table

Revision ID: c7bfd84cbca4
Revises: 9c1dc6720df0
Create Date: 2026-09-15 15:30:19.972245

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7bfd84cbca4"
down_revision: str | Sequence[str] | None = "9c1dc6720df0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "handoffs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("motivo", sa.String(length=24), nullable=False),
        sa.Column("resumen_requerimiento", sa.Text(), nullable=False),
        sa.Column("canal_preferido", sa.String(length=16), nullable=True),
        sa.Column("urgencia", sa.String(length=8), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_handoffs_session_id"), "handoffs", ["session_id"], unique=False)
    op.create_index(op.f("ix_handoffs_status"), "handoffs", ["status"], unique=False)
    op.create_index(op.f("ix_handoffs_user_id"), "handoffs", ["user_id"], unique=False)
    op.create_index(
        "ux_handoffs_one_open_per_session",
        "handoffs",
        ["session_id"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ux_handoffs_one_open_per_session",
        table_name="handoffs",
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.drop_index(op.f("ix_handoffs_user_id"), table_name="handoffs")
    op.drop_index(op.f("ix_handoffs_status"), table_name="handoffs")
    op.drop_index(op.f("ix_handoffs_session_id"), table_name="handoffs")
    op.drop_table("handoffs")
    # ### end Alembic commands ###
